# Part A: Conceptual Foundation
# Tensor Types with NumPy

In [97]:
import numpy as np

# 0D Tensor (Scalar)
scalar = np.array(10)
print("Scalar:", scalar)

# 1D Tensor (Vector)
vector = np.array([1, 2, 3])
print("Vector:", vector)

# 2D Tensor (Matrix)
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# 3D Tensor
tensor_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor:\n", tensor_3d)

Scalar: 10
Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

# Tensor Properties

In [98]:
print("Shape:", tensor_3d.shape)   # Dimensions
print("Size:", tensor_3d.size)     # Total elements
print("Dimensions:", tensor_3d.ndim)  # Number of axes

Shape: (2, 2, 2)
Size: 8
Dimensions: 3

# Basic Tensor Operations

In [99]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Addition
print(a + b)

# Multiplication
print(a * b)

# Dot Product
print(np.dot(a, b))

[5 7 9]
[ 4 10 18]
32

# PART B: DATA ACQUISITION

# load CSV files (main transactions dataset).
# Parse JSON files (customer metadata).

In [100]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 1000

df = pd.DataFrame({
    "customer_id": range(1, n+1),
    "age": np.random.randint(18, 70, n),
    "gender": np.random.choice(["Male", "Female", "Other"], n),
    "region": np.random.choice(["North", "South", "East", "West"], n),
    "education_level": np.random.choice(["Primary", "Secondary", "Graduate", "Post-Graduate"], n),
    "employment_type": np.random.choice(["Salaried", "Self-Employed", "Unemployed"], n),
    "annual_income": np.random.normal(500000, 200000, n),
    "loan_amount": np.random.normal(200000, 100000, n),
    "loan_purpose": np.random.choice(["Home", "Car", "Education", "Business"], n),
    "credit_score": np.random.randint(300, 850, n),
    "repayment_history": np.random.randint(0, 12, n),
    "transaction_count": np.random.randint(10, 200, n),
    "spending_ratio": np.random.uniform(0.1, 0.9, n),
    "join_date": pd.date_range(start="2020-01-01", periods=n),
    "default_flag": np.random.choice([0,1], n)
})

# Inject missing values
for col in ["age","annual_income","credit_score","employment_type"]:
    df.loc[df.sample(frac=0.1).index, col] = np.nan

df.to_csv("customers.csv", index=False)
df.to_json("customers.json", orient="records")

# Fetch records from SQL (loan repayment history).

In [101]:
import sqlite3

conn = sqlite3.connect("customers.db")
df.to_sql("customers", conn, if_exists="replace", index=False)
conn.close()

# Fetch data from a dummy API (external economic indicators).

In [102]:
def fetch_api():
    return pd.DataFrame({
        "economic_index": np.random.uniform(80,120,1000)
    })

api_data = fetch_api()

In [103]:
df

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,56.0,Other,North,Graduate,Unemployed,NaN,114669.669317,Home,457.0,11,91,0.212888,2020-01-01,0
1,2,69.0,Other,West,Post-Graduate,Self-Employed,4.851578e+05,208528.423349,Car,368.0,10,187,0.587038,2020-01-02,0
2,3,NaN,Other,South,Primary,NaN,7.174928e+05,318049.087797,Home,NaN,4,126,0.243437,2020-01-03,1
3,4,32.0,Male,South,Graduate,Salaried,NaN,427840.198653,Home,384.0,3,104,0.280610,2020-01-04,1
4,5,60.0,Other,East,Primary,Salaried,4.154733e+05,265736.496339,Business,566.0,3,42,0.120112,2020-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,60.0,Male,West,Primary,Salaried,5.699539e+05,210565.382503,Car,590.0,8,109,0.279925,2022-09-22,0
996,997,64.0,Male,North,Primary,Unemployed,4.407908e+05,339462.538821,Business,352.0,9,185,0.161289,2022-09-23,1
997,998,62.0,Male,East,Primary,Self-Employed,NaN,95478.563768,Car,409.0,4,83,0.748413,2022-09-24,1
998,999,35.0,Female,North,Primary,Unemployed,1.010937e+06,160360.447982,Car,303.0,6,193,0.881202,2022-09-25,1
999,1000,55.0,Male,West,Primary,Unemployed,3.715611e+05,183103.479334,Education,346.0,7,104,0.615738,2022-09-26,0

# PART C: DATA UNDERSTANDING & CLEANING

# 4.Explore the dataset using Pandas (.info(),.describe ()).

In [104]:
import pandas as pd

df = pd.read_csv("customers.csv")

# Basic info
df.info()

# Statistical summary
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1000 non-null   int64
 1   age                900 non-null    float64
 2   gender             1000 non-null   object
 3   region             1000 non-null   object
 4   education_level    1000 non-null   object
 5   employment_type    900 non-null    object
 6   annual_income      900 non-null    float64
 7   loan_amount        1000 non-null   float64
 8   loan_purpose       1000 non-null   object
 9   credit_score       900 non-null    float64
 10  repayment_history  1000 non-null   int64
 11  transaction_count  1000 non-null   int64
 12  spending_ratio     1000 non-null   float64
 13  join_date          1000 non-null   object
 14  default_flag       1000 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 117.3+ KB

customer_id            0
age                  100
gender                 0
region                 0
education_level        0
employment_type      100
annual_income        100
loan_amount            0
loan_purpose           0
credit_score         100
repayment_history      0
transaction_count      0
spending_ratio         0
join_date              0
default_flag           0
dtype: int64

# 5. Perform Pandas Profiling to generate a data quality report.

In [105]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\macwan alex\anaconda3\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (2.10.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\macwan alex\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (2.1.3)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=4 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\macwan alex\anaconda3\lib\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\macwan alex\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\macwan alex\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\macwan alex\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\macwan alex\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\macwan alex\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\macwan alex\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\macwan alex\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\macwan alex\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\macwan alex\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\macwan alex\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in c:\users\macwan alex\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\macwan alex\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\macwan alex\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (24.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\macwan alex\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: puremagic in c:\users\macwan alex\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\macwan alex\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [106]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, explorative=True)
profile.to_file("data_quality_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 15/15 [00:00<00:00, 376.94it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# 6. Handle missing data with:
# • Simple Imputer (numerical: mean/median).

In [107]:
from sklearn.impute import SimpleImputer

# Mean Imputation
mean_imputer = SimpleImputer(strategy="mean")
df[['age','annual_income','credit_score']] = mean_imputer.fit_transform(
    df[['age','annual_income','credit_score']]
)

# Median Imputation (optional alternative)
median_imputer = SimpleImputer(strategy="median")
df[['loan_amount']] = median_imputer.fit_transform(df[['loan_amount']])

# • Simple Imputer (categorical: most frequent).

In [108]:
cat_imputer = SimpleImputer(strategy="most_frequent")

df[['employment_type','gender']] = cat_imputer.fit_transform(
    df[['employment_type','gender']]
)

# • Most Frequent Category Imputation.

In [109]:
cat_imputer = SimpleImputer(strategy="most_frequent")

df[['employment_type','gender']] = cat_imputer.fit_transform(
    df[['employment_type','gender']]
)

# • Missing Indicator + Random Sample Imputation.

In [110]:
# Indicator column
df['income_missing_flag'] = df['annual_income'].isnull().astype(int)

# Random sample imputation (clean version)
missing_count = df['annual_income'].isnull().sum()

random_values = df['annual_income'].dropna().sample(missing_count, replace=True)

df.loc[df['annual_income'].isnull(), 'annual_income'] = random_values.values

# • KNN Imputer (multivariate).

In [111]:
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(n_neighbors=5)

df[['annual_income','loan_amount','credit_score']] = knn_imputer.fit_transform(
    df[['annual_income','loan_amount','credit_score']]
)

# • MICE Algorithm.

In [112]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

mice_imputer = IterativeImputer(random_state=42)

df[['annual_income','loan_amount','credit_score']] = mice_imputer.fit_transform(
    df[['annual_income','loan_amount','credit_score']]
)

# • Complete Case Analysis (dropping rows/columns).

In [113]:
# Drop rows with missing values
df_drop_rows = df.dropna()

# Drop columns with too many missing values (example threshold)
df_drop_cols = df.dropna(axis=1, thresh=int(0.7*len(df)))

# Part D: Outlier Handling

In [114]:
num_cols = ['annual_income','loan_amount','credit_score']

# 7. Detect and treat outliers using:
# • Z-score Method.

In [115]:
from scipy import stats
import numpy as np

z_scores = np.abs(stats.zscore(df[num_cols]))

# Keep rows where all z-scores < 3
df_z = df[(z_scores < 3).all(axis=1)]

print("Before:", df.shape)
print("After Z-score:", df_z.shape)

Before: (1000, 16)
After Z-score: (997, 16)

# • IQR Method.

In [116]:
df_iqr = df.copy()

for col in num_cols:
    Q1 = df_iqr[col].quantile(0.25)
    Q3 = df_iqr[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_iqr = df_iqr[(df_iqr[col] >= lower) & (df_iqr[col] <= upper)]

print("After IQR:", df_iqr.shape)

After IQR: (990, 16)

# • Percentile Method.

In [117]:
df_pct = df.copy()

for col in num_cols:
    lower = df_pct[col].quantile(0.01)
    upper = df_pct[col].quantile(0.99)

    df_pct = df_pct[(df_pct[col] >= lower) & (df_pct[col] <= upper)]

print("After Percentile:", df_pct.shape)

After Percentile: (943, 16)

# • Winsorization Technique.

In [118]:
from scipy.stats.mstats import winsorize

df_win = df.copy()

for col in num_cols:
    df_win[col] = winsorize(df_win[col], limits=[0.05, 0.05])

print("After Winsorization:", df_win.shape)

After Winsorization: (1000, 16)

# Part E: Feature Engineering
# 8. Handle variable types:
# • Mixed Variables (numeric + categorical).

In [119]:
# Identify columns
num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print("Numerical:", num_cols)
print("Categorical:", cat_cols)

Numerical: Index(['customer_id', 'age', 'annual_income', 'loan_amount', 'credit_score',
       'repayment_history', 'transaction_count', 'spending_ratio',
       'default_flag', 'income_missing_flag'],
      dtype='object')
Categorical: Index(['gender', 'region', 'education_level', 'employment_type',
       'loan_purpose', 'join_date'],
      dtype='object')

# • Date & Time variables → extract Year, Month, Day, Weekday.

In [120]:
df['join_date'] = pd.to_datetime(df['join_date'])

df['year'] = df['join_date'].dt.year
df['month'] = df['join_date'].dt.month
df['day'] = df['join_date'].dt.day
df['weekday'] = df['join_date'].dt.weekday

# 9. Encoding categorical variables:
# • Ordinal Encoding (education levels).

In [121]:
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder(categories=[['Primary','Secondary','Graduate','Post-Graduate']])

df['education_level'] = ord_enc.fit_transform(df[['education_level']])

# • Label Encoding (binary features).

In [122]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])

# • One-Hot Encoding (regions, loan purpose).

In [123]:
df = pd.get_dummies(df, columns=['region','loan_purpose'], drop_first=True)

# 10. Encoding numerical features:
# • Binning (discretize income into groups).

In [124]:
df['income_bin'] = pd.cut(df['annual_income'], bins=4, labels=False)

# • Binarization (flag if> threshold).

In [125]:
df['credit_flag'] = (df['credit_score'] > 700).astype(int)

# • Quantile Binning.

In [126]:
df['income_quantile_bin'] = pd.qcut(df['annual_income'], q=4, labels=False)

# • K-Means Binning.

In [127]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)

df['transaction_cluster'] = kmeans.fit_predict(df[['transaction_count']])

C:\Users\macwan alex\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(

# Part F: Feature Scaling

In [128]:
num_cols = ['annual_income','loan_amount','transaction_count','spending_ratio']

# 11. Apply multiple scaling methods:
# Standardization (Z-score scaling).

In [129]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

df_std = df.copy()
df_std[num_cols] = std_scaler.fit_transform(df_std[num_cols])

df_std.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,income_bin,credit_flag,income_quantile_bin,transaction_cluster
0,1,56.000000,2,2.0,Unemployed,-3.164931e-16,-0.833738,457.000000,11,-0.237755,...,True,False,False,False,False,True,2,0,1,2
1,2,69.000000,2,3.0,Self-Employed,-6.623697e-02,0.105756,368.000000,10,1.520004,...,False,False,True,True,False,False,2,0,1,3
2,3,43.972222,2,0.0,Salaried,1.197041e+00,1.202021,574.785556,4,0.403094,...,False,True,False,False,False,True,2,0,3,1
3,4,32.000000,1,2.0,Salaried,-3.164931e-16,2.300992,384.000000,3,0.000275,...,False,True,False,False,False,True,2,0,1,2
4,5,60.000000,2,0.0,Salaried,-4.451333e-01,0.678390,566.000000,3,-1.134945,...,False,False,False,False,False,False,1,0,1,0

# Normalization.

In [130]:
from sklearn.preprocessing import Normalizer

norm = Normalizer()

df_norm = df.copy()
df_norm[num_cols] = norm.fit_transform(df_norm[num_cols])

df_norm.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,income_bin,credit_flag,income_quantile_bin,transaction_cluster
0,1,56.000000,2,2.0,Unemployed,0.974435,0.224672,457.000000,11,0.000178,...,True,False,False,False,False,True,2,0,1,2
1,2,69.000000,2,3.0,Self-Employed,0.918731,0.394885,368.000000,10,0.000354,...,False,False,True,True,False,False,2,0,1,3
2,3,43.972222,2,0.0,Salaried,0.914207,0.405248,574.785556,4,0.000161,...,False,True,False,False,False,True,2,0,3,1
3,4,32.000000,1,2.0,Salaried,0.758089,0.652151,384.000000,3,0.000159,...,False,True,False,False,False,True,2,0,1,2
4,5,60.000000,2,0.0,Salaried,0.842425,0.538814,566.000000,3,0.000085,...,False,False,False,False,False,False,1,0,1,0

# Min-Max Scaling.

In [131]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

df_minmax = df.copy()
df_minmax[num_cols] = minmax.fit_transform(df_minmax[num_cols])

df_minmax.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,income_bin,credit_flag,income_quantile_bin,transaction_cluster
0,1,56.000000,2,2.0,Unemployed,0.518492,0.369612,457.000000,11,0.428571,...,True,False,False,False,False,True,2,0,1,2
1,2,69.000000,2,3.0,Self-Employed,0.508955,0.538742,368.000000,10,0.936508,...,False,False,True,True,False,False,2,0,1,3
2,3,43.972222,2,0.0,Salaried,0.690845,0.736094,574.785556,4,0.613757,...,False,True,False,False,False,True,2,0,3,1
3,4,32.000000,1,2.0,Salaried,0.518492,0.933934,384.000000,3,0.497354,...,False,True,False,False,False,True,2,0,1,2
4,5,60.000000,2,0.0,Salaried,0.454401,0.641829,566.000000,3,0.169312,...,False,False,False,False,False,False,1,0,1,0

# MaxAbs Scaling.

In [132]:
from sklearn.preprocessing import MaxAbsScaler

maxabs = MaxAbsScaler()

df_maxabs = df.copy()
df_maxabs[num_cols] = maxabs.fit_transform(df_maxabs[num_cols])

df_maxabs.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,income_bin,credit_flag,income_quantile_bin,transaction_cluster
0,1,56.000000,2,2.0,Unemployed,0.447091,0.246865,457.000000,11,0.457286,...,True,False,False,False,False,True,2,0,1,2
1,2,69.000000,2,3.0,Self-Employed,0.436140,0.448927,368.000000,10,0.939698,...,False,False,True,True,False,False,2,0,1,3
2,3,43.972222,2,0.0,Salaried,0.645002,0.684707,574.785556,4,0.633166,...,False,True,False,False,False,True,2,0,3,1
3,4,32.000000,1,2.0,Salaried,0.447091,0.921070,384.000000,3,0.522613,...,False,True,False,False,False,True,2,0,1,2
4,5,60.000000,2,0.0,Salaried,0.373496,0.572087,566.000000,3,0.211055,...,False,False,False,False,False,False,1,0,1,0

# Robust Scaling.

In [133]:
from sklearn.preprocessing import RobustScaler

robust = RobustScaler()

df_robust = df.copy()
df_robust[num_cols] = robust.fit_transform(df_robust[num_cols])

df_robust.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,income_bin,credit_flag,income_quantile_bin,transaction_cluster
0,1,56.000000,2,2.0,Unemployed,0.000000,-0.585497,457.000000,11,-0.120548,...,True,False,False,False,False,True,2,0,1,2
1,2,69.000000,2,3.0,Self-Employed,-0.050804,0.108228,368.000000,10,0.931507,...,False,False,True,True,False,False,2,0,1,3
2,3,43.972222,2,0.0,Salaried,0.918129,0.917713,574.785556,4,0.263014,...,False,True,False,False,False,True,2,0,3,1
3,4,32.000000,1,2.0,Salaried,0.000000,1.729196,384.000000,3,0.021918,...,False,True,False,False,False,True,2,0,1,2
4,5,60.000000,2,0.0,Salaried,-0.341417,0.531062,566.000000,3,-0.657534,...,False,False,False,False,False,False,1,0,1,0

# Part G: Feature Construction & Transformation
# 12. Apply transformations:
#  FunctionTransformer → log transform, reciprocal, square root.

In [134]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# Log Transform
log_transform = FunctionTransformer(np.log1p)
df['log_spending'] = log_transform.fit_transform(df[['spending_ratio']])

# Square Root Transform
sqrt_transform = FunctionTransformer(np.sqrt)
df['sqrt_spending'] = sqrt_transform.fit_transform(df[['spending_ratio']])

# Reciprocal Transform (avoid division by zero)
df['reciprocal_spending'] = 1 / (df['spending_ratio'] + 1e-5)

# PowerTransformer → Box-Cox and Yeo-Johnson.

In [135]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method='yeo-johnson')

df[['annual_income','loan_amount']] = pt.fit_transform(
    df[['annual_income','loan_amount']]
)

# Column Transformer → apply different preprocessing steps to different columns.

In [136]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_cols = ['annual_income','loan_amount']
cat_cols = ['gender']

ct = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(), cat_cols)
])

transformed_data = ct.fit_transform(df)

# 13. Construct new features:
# Debt-to-Income ratio.

In [137]:
df['debt_to_income'] = df['loan_amount'] / (df['annual_income'] + 1e-5)

# Average monthly transactions.

In [138]:
df['avg_monthly_txn'] = df['transaction_count'] / 6

# Spending-to-Income ratio.

In [139]:
df['spending_to_income'] = df['spending_ratio'] / (df['annual_income'] + 1e-5)

In [140]:
df.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,income_bin,credit_flag,income_quantile_bin,transaction_cluster,log_spending,sqrt_spending,reciprocal_spending,debt_to_income,avg_monthly_txn,spending_to_income
0,1,56.000000,2,2.0,Unemployed,-0.002906,-0.834331,457.000000,11,91,...,2,0,1,2,0.193004,0.461398,4.697091,288.078051,15.166667,-73.505915
1,2,69.000000,2,3.0,Self-Employed,-0.069280,0.105443,368.000000,10,187,...,2,0,1,3,0.461870,0.766184,1.703437,-1.522192,31.166667,-8.474607
2,3,43.972222,2,0.0,Salaried,1.199783,1.202459,574.785556,4,126,...,2,0,3,1,0.217879,0.493393,4.107670,1.002223,21.000000,0.202899
3,4,32.000000,1,2.0,Salaried,-0.002906,2.302489,384.000000,3,104,...,2,0,1,2,0.247337,0.529727,3.563532,-795.003783,17.333333,-96.889237
4,5,60.000000,2,0.0,Salaried,-0.448535,0.678424,566.000000,3,42,...,1,0,1,0,0.113428,0.346571,8.324885,-1.512567,7.000000,-0.267793

# Part H: Final Deliverable
# 14. Provide a final cleaned and transformed dataset.

In [141]:
df.to_csv("final_cleaned_dataset.csv", index=False)

print("Final dataset shape:", df.shape)

Final dataset shape: (1000, 34)